TRAINED_GLOSSES = ['minum', 'berjalan', 'berlari', 'bola', 'dari', 'hi',
                   'jangan', 'mohon', 'pen', 'teh tarik', 'tolong'] # TODO: Make it dynamic
NUM_CLASSES = len(TRAINED_GLOSSES) # TODO: Make it dynamic

WEIGHT_PATH = "trained_model.pth"
SCALER_PATH = "scaler.bin"
FRAME_SEQUENCE_LENGTH = 30
PREDICTION_THRESHOLD = 0.7

MIN_DETECTION_CONFIDENCE = 0.5
MIN_TRACKING_CONFIDENCE = 0.5

POSE_NUM_KEYPOINTS = 33
FACE_NUM_KEYPOINTS = 0
LEFT_HAND_NUM_KEYPOINTS = 21
RIGHT_HAND_NUM_KEYPOINTS = 21

POSE_INPUT_DIM = POSE_NUM_KEYPOINTS * 4
FACE_INPUT_DIM = 0
LEFT_HAND_INPUT_DIM = LEFT_HAND_NUM_KEYPOINTS * 3
RIGHT_HAND_INPUT_DIM = RIGHT_HAND_NUM_KEYPOINTS * 3

NUM_FEATURES = POSE_INPUT_DIM + FACE_INPUT_DIM + LEFT_HAND_INPUT_DIM + RIGHT_HAND_INPUT_DIM